GSE11341
========================================================

##按照丰核要求做报告##

载入数据
```{r echo=FALSE}
setwd("~/Projects/microarray_data/GSE11341/CELs")
library(affy)
gse <- ReadAffy()
gse_sample <- read.csv("../Samples.csv")
sampleNames(gse) <- sub("\\.CEL$","",sampleNames(gse))
mt <- match(gse_sample$SampleID,sampleNames(gse))
vmd <- data.frame(labelDescription=c("Sample ID","Tissue type","Oxygen status","Repeat times"))
phenoData(gse) <- new("AnnotatedDataFrame",data=gse_sample[mt,],varMetadata=vmd)
sampleNames(gse) <- sampleNames(gse@protocolData)

factor(c(rep("lightblue",11),rep("pink",12))) %:>% 
  (group_color <- as.character(.))
# 或者
# colf1 <- gl(1,11,labels="lightblue")
# colf2 <- gl(1,12,labels="pink")
# factor(c(levels(colf1)[colf1],levels(colf2)[colf2])) %:>% 
#   (group_color <- as.character(.))

# 如果要调整cel文件顺序，使用类似命令即可
# sampleNames(gse)
## "GSM286407" "GSM286408" ...
# gse <- gse[,c("GSM286408","GSM286407", ...)]

library(annotate)
gse_annotation <- annPkgName(gse@annotation,type="db")
if(!require(gse_annotation,character.only=T)) {
  biocLite(gse_annotation)
  library(gse_annotation,character.only=T)
}
```

质量检验

```{r echo=FALSE}
library(simpleaffy)
qc(gse) %>>% plot

library(affyPLM)
par(mar=c(8,3,2,2))
fitPLM(gse) %:>% {
  Mbox(.,main="RLE",col=group_color,las=3,ylim=c(-0.4,0.4),whisklty=0)
  boxplot(.,main="NUSE",col=group_color,las=3,ylim=c(0.95,1.1),whisklty=0)
}

par(mar=c(5,3,3,0))
plotRNAdeg <- function(x){
  pp <- function(x,col){
    plotAffyRNAdeg(x,col=col)
    legend("topleft",rownames(pData(gse)),
           col=col,lwd=1,ncol=4,inset=0.05,cex=0.5)
  }
  rainbow(23) %:>% pp(x,.)
}
AffyRNAdeg(gse) %>>% plotRNAdeg
```

均一化

```{r echo=FALSE}
gse_rma <- rma(gse)
par(mar=c(8,3,2,2))
boxplot(gse_rma,col=group_color,las=3,main="RMA")
```

选取差异表达基因

```{r echo=FALSE}
library(limma)
gse_eset <- exprs(gse_rma)
levels <- factor(paste(gse_sample$Tissue,gse_sample$Oxygen,sep="."))
design <- model.matrix(~0+levels)
colnames(design) <- levels(levels)
corfit <- duplicateCorrelation(gse_eset,design,block=gse_sample$Repeat)
fit <- lmFit(gse_eset,design,block=gse_sample$Repeat,correlation=corfit$consensus.correlation)
cm <- makeContrasts(
  Cardiac3=Cardiac.cells_3hrHypoxia-Cardiac.cells_Normoxia,
  Cardiac24=Cardiac.cells_24hrHypoxia-Cardiac.cells_Normoxia,
  Cardiac48=Cardiac.cells_48hrHypoxia-Cardiac.cells_Normoxia,
  Lung3=Lung.cells_3hrHypoxia-Lung.cells_Normoxia,
  Lung24=Lung.cells_24hrHypoxia-Lung.cells_Normoxia,
  Lung48=Lung.cells_48hrHypoxia-Lung.cells_Normoxia,
  levels=design)
# 选取ajust p-value < 0.01的基因
# 各个条件下对应值是差异表达值的log2对数值
contrasts.fit(fit,cm) %>>% eBayes %:>% (dif <- topTable(.,coef=c("Cardiac3","Cardiac24","Cardiac48","Lung3","Lung24","Lung48"),number=1000,p.value=0.01))
# fit2 <- contrasts.fit(fit,cm)
# fit2 <- eBayes(fit2)
# dif <- topTable(fit2,coef=c("Cardiac3","Cardiac24","Cardiac48","Lung3","Lung24","Lung48"),number=335)

dif$symbols <- getSYMBOL(rownames(dif),gse_annotation)
dif$EntrezID <- getEG(rownames(dif),gse_annotation)

# 区分上调基因，下调基因和上下调不一致基因
# 剔除没有注释名称的基因
d <- dif[!is.na(dif$symbols),]
d_upORdown <- d[d$Cardiac3 < 0 |
                  d$Cardiac24 < 0 |
                  d$Cardiac48 < 0 |
                  d$Lung3 < 0 |
                  d$Lung24 < 0 |
                  d$Lung48 < 0,]
d_upORdown <- d_upORdown[!(d_upORdown$Cardiac3 < 0 &
                             d_upORdown$Cardiac24 < 0 &
                             d_upORdown$Cardiac48 < 0 &
                             d_upORdown$Lung3 < 0 &
                             d_upORdown$Lung24 < 0 &
                             d_upORdown$Lung48 < 0),]
d_down <- d[d$Cardiac3 < 0 &
              d$Cardiac24 < 0 &
              d$Cardiac48 < 0 &
              d$Lung3 < 0 &
              d$Lung24 < 0 &
              d$Lung48 < 0,]
d_up <- d[!(d$Cardiac3 < 0 |
              d$Cardiac24 < 0 |
              d$Cardiac48 < 0 |
              d$Lung3 < 0 |
              d$Lung24 < 0 |
              d$Lung48 < 0),]
```

热图

```{r echo=FALSE,}
library(pheatmap)
selected <- gse_eset[rownames(d),]
rownames(selected) <- d$symbols
pheatmap(selected,color=colorRampPalette(c("green","black","red"))(100),border_color=NA)
```

统计分析及可视化

```{r echo=FALSE}
# 换成clusterProfiler包，出柱状图
library(clusterProfiler)
ego_up <- enrichGO(gene=d_up$EntrezID,ont="BP",pvalueCutoff=0.01,readable=T)
ego_down <- enrichGO(gene=d_down$EntrezID,ont="BP",pvalueCutoff=0.01,readable=T)
ego_upORdown <- enrichGO(gene=d_upORdown$EntrezID,ont="BP",pvalueCutoff=0.01,readable=T)

# library(GOstats)
# entrezUniverse <- unique(unlist(mget(rownames(gse_eset),hgu133aENTREZID)))
# entrezSelected <- unique(d[!is.na(d$EntrezID),"EntrezID"])
# params <- new("GOHyperGParams",geneIds=entrezSelected,universeGeneIds=entrezUniverse,annotation=gse_annotation,ontology="BP",pvalueCutoff=0.001,conditional=F,testDirection="over")
# hgOver <- hyperGTest(params)
# bp <- summary(hgOver)
# htmlReport(hgOver,file="../ALL_go.html")
# library(Rgraphviz)
# ghandle <- goDag(hgOver)
# subGHandle <- subGraph(snodes=as.character(summary(hgOver)[,1]),graph=ghandle)
# plot(subGHandle)

# 分别对上调，下调和上下调不明确的基因进行KEGG分析
# 由于KEGG缺乏维护，现在开始流行Reactome分析。不过ReactomePA和clusterProfiler包分析enrichPathway和enrichKEGG结果数量明显少于GeneAnswers包，还有赖于未来的项目验证。
# library(ReactomePA)
# epa_up <- enrichPathway(gene=d_up$EntrezID,pvalueCutoff=0.01,readable=T)
# epa_down <- enrichPathway(gene=d_down$EntrezID,pvalueCutoff=0.01,readable=T)
# epa_upORdown <- enrichPathway(gene=d_upORdown$EntrezID,pvalueCutoff=0.01,readable=T)

library(GeneAnswers)
humanGeneInput_up <- d_up[,c("EntrezID","F","adj.P.Val")]
humanExpr_up <- gse_eset[match(rownames(d_up),rownames(gse_eset)),]
humanExpr_up <- cbind(humanGeneInput_up[,"EntrezID"],humanExpr_up)
humanGeneInput_up <- humanGeneInput_up[!is.na(humanGeneInput_up[,1]),]
humanExpr_up <- humanExpr_up[!is.na(humanExpr_up[,1]),]
y_up <- geneAnswersBuilder(humanGeneInput_up,"org.Hs.eg.db",categoryType="KEGG",testType="hyperG",pvalueT=0.01,geneExpressionProfile=humanExpr_up,verbose=F)
yy_up <- geneAnswersReadable(y_up,verbose=F)
geneAnswersConceptNet(yy_up,colorValueColumn="F",centroidSize="pvalue",output="interactive")
yyy_up <- geneAnswersSort(yy_up,sortBy="pvalue")
geneAnswersHeatmap(yyy_up)

humanGeneInput_down <- d_down[,c("EntrezID","F","adj.P.Val")]
humanExpr_down <- gse_eset[match(rownames(d_down),rownames(gse_eset)),]
humanExpr_down <- cbind(humanGeneInput_down[,"EntrezID"],humanExpr_down)
humanGeneInput_down <- humanGeneInput_down[!is.na(humanGeneInput_down[,1]),]
humanExpr_down <- humanExpr_down[!is.na(humanExpr_down[,1]),]
y_down <- geneAnswersBuilder(humanGeneInput_down,"org.Hs.eg.db",categoryType="KEGG",testType="hyperG",pvalueT=0.01,geneExpressionProfile=humanExpr_down,verbose=F)
yy_down <- geneAnswersReadable(y_down,verbose=F)
geneAnswersConceptNet(yy_down,colorValueColumn="F",centroidSize="pvalue",output="interactive")
yyy_down <- geneAnswersSort(yy_down,sortBy="pvalue")
geneAnswersHeatmap(yyy_down)

humanGeneInput_upORdown <- d_upORdown[,c("EntrezID","F","adj.P.Val")]
humanExpr_upORdown <- gse_eset[match(rownames(d_upORdown),rownames(gse_eset)),]
humanExpr_upORdown <- cbind(humanGeneInput_upORdown[,"EntrezID"],humanExpr_upORdown)
humanGeneInput_upORdown <- humanGeneInput_upORdown[!is.na(humanGeneInput_upORdown[,1]),]
humanExpr_upORdown <- humanExpr_upORdown[!is.na(humanExpr_upORdown[,1]),]
y_upORdown <- geneAnswersBuilder(humanGeneInput_upORdown,"org.Hs.eg.db",categoryType="KEGG",testType="hyperG",pvalueT=0.01,geneExpressionProfile=humanExpr_upORdown,verbose=F)
yy_upORdown <- geneAnswersReadable(y_upORdown,verbose=F)
geneAnswersConceptNet(yy_upORdown,colorValueColumn="F",centroidSize="pvalue",output="interactive")
yyy_upORdown <- geneAnswersSort(yy_upORdown,sortBy="pvalue")
geneAnswersHeatmap(yyy_upORdown)
```